version: "3.9"

services:

  database:
    image: postgres:14.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - database-data:/var/lib/postgresql/data

  api-order:
    image: order_service:1.0.2
    build: ./orders
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      DB_URL: postgresql://postgres:postgres@database:5432/postgres
    volumes:
      - ./orders:/orders
  order-migration:
    image: order_migration:1.0.0
    build: ./orders
    depends_on:
      - database
    environment:
      DB_URL: postgresql://postgres:postgres@database:5432/postgres
#  api-kitchen:
#    image: kitchen_service:1.0.0
#    build: ./kitchen
#    ports:
#      - 5000:5000
#    depends_on:
#      - database
#    environment:
#      DB_URL: postgresql://postgres:postgres@database:5432/postgres
#    volumes:
#      - ./kitchen:/kitchen


volumes:
  database-data:
